export const VehicleDatabase = {
  brands: [
    { id: 1,  name: 'Acura' },
    { id: 4,  name: 'Audi' },
  
    { id: 6,  name: 'BMW' },
    { id: 8,  name: 'Buick' },
    { id: 9,  name: 'Cadillac' },
    { id: 10, name: 'Chevrolet' },
    { id: 11, name: 'Chrysler' },
    { id: 16, name: 'Dodge' },
    { id: 19, name: 'Fiat' },
    { id: 20, name: 'Ford' },
    { id: 22, name: 'GMC' },
    { id: 23, name: 'Honda' },
    { id: 25, name: 'Hyundai' },
    { id: 26, name: 'Infiniti' },
    { id: 27, name: 'Isuzu' },
    { id: 29, name: 'Jeep' },
    { id: 30, name: 'Kia' },
    { id: 34, name: 'Land Rover' },
    { id: 35, name: 'Lexus' },
    { id: 36, name: 'Lincoln' },
    { id: 40, name: 'Mazda' },
    { id: 42, name: 'Mercedes-Benz' },
    { id: 45, name: 'Mini' },
    { id: 46, name: 'Mitsubishi' },
    { id: 47, name: 'Nissan' },
    { id: 52, name: 'Pontiac' },
    { id: 53, name: 'Porsche' },
    { id: 54, name: 'Ram' },
    { id: 55, name: 'Renault' }, 
    { id: 62, name: 'Smart' },
    { id: 63, name: 'Subaru' },
    { id: 64, name: 'Suzuki' },
    { id: 65, name: 'Tesla' },
    { id: 66, name: 'Toyota' },
    { id: 68, name: 'Volkswagen' },
    { id: 69, name: 'Volvo' },
    { id: 70, name: 'Autre marque' }   // gardé en dernier volontairement
  ],

  modelsByBrand: {
    'Acura': [
      { id: 1, name: 'ILX' },
      { id: 2, name: 'TLX' },
      { id: 3, name: 'RLX' },
      { id: 4, name: 'RDX' },
      { id: 5, name: 'MDX' },
      { id: 6, name: 'NSX' },
      { id: 7, name: 'TSX' },
      { id: 8, name: 'RSX' },
      { id: 9, name: 'Autre modèle Acura' }
    ],
    'Alfa Romeo': [
      { id: 10, name: 'Giulia' },
      { id: 11, name: 'Stelvio' },
      { id: 12, name: '4C' },
      { id: 13, name: 'Giulietta' },
      { id: 14, name: 'MiTo' },
      { id: 15, name: '159' },
      { id: 16, name: '147' },
      { id: 17, name: '156' },
      { id: 18, name: 'Spider' },
      { id: 19, name: 'Brera' },
      { id: 20, name: 'Autre modèle Alfa Romeo' }
    ],
    'Aston Martin': [
      { id: 21, name: 'DB11' },
      { id: 22, name: 'DB9' },
      { id: 23, name: 'DBS' },
      { id: 24, name: 'Vantage' },
      { id: 25, name: 'Vanquish' },
      { id: 26, name: 'Rapide' },
      { id: 27, name: 'DBX' },
      { id: 28, name: 'Valkyrie' },
      { id: 29, name: 'Autre modèle Aston Martin' }
    ],
    'Audi': [
      { id: 30, name: 'A1' },
      { id: 31, name: 'A3' },
      { id: 32, name: 'A4' },
      { id: 33, name: 'A5' },
      { id: 34, name: 'A6' },
      { id: 35, name: 'A7' },
      { id: 36, name: 'A8' },
      { id: 37, name: 'Q2' },
      { id: 38, name: 'Q3' },
      { id: 39, name: 'Q4 e-tron' },
      { id: 40, name: 'Q5' },
      { id: 41, name: 'Q7' },
      { id: 42, name: 'Q8' },
      { id: 43, name: 'TT' },
      { id: 44, name: 'R8' },
      { id: 45, name: 'e-tron' },
      { id: 46, name: 'e-tron GT' },
      { id: 47, name: 'RS3' },
      { id: 48, name: 'RS4' },
      { id: 49, name: 'RS5' },
      { id: 50, name: 'RS6' },
      { id: 51, name: 'RS7' },
      { id: 52, name: 'S3' },
      { id: 53, name: 'S4' },
      { id: 54, name: 'S5' },
      { id: 55, name: 'S6' },
      { id: 56, name: 'S7' },
      { id: 57, name: 'S8' },
      { id: 58, name: 'SQ5' },
      { id: 59, name: 'SQ7' },
      { id: 60, name: 'SQ8' },
      { id: 61, name: 'Autre modèle Audi' }
    ],

    'BMW': [
      { id: 71, name: 'Série 1' },
      { id: 72, name: 'Série 2' },
      { id: 73, name: 'Série 3' },
      { id: 74, name: 'Série 4' },
      { id: 75, name: 'Série 5' },
      { id: 76, name: 'Série 6' },
      { id: 77, name: 'Série 7' },
      { id: 78, name: 'Série 8' },
      { id: 79, name: 'X1' },
      { id: 80, name: 'X2' },
      { id: 81, name: 'X3' },
      { id: 82, name: 'X4' },
      { id: 83, name: 'X5' },
      { id: 84, name: 'X6' },
      { id: 85, name: 'X7' },
      { id: 86, name: 'Z3' },
      { id: 87, name: 'Z4' },
      { id: 88, name: 'Z8' },
      { id: 89, name: 'i3' },
      { id: 90, name: 'i4' },
      { id: 91, name: 'i8' },
      { id: 92, name: 'iX' },
      { id: 93, name: 'iX3' },
      { id: 94, name: 'M2' },
      { id: 95, name: 'M3' },
      { id: 96, name: 'M4' },
      { id: 97, name: 'M5' },
      { id: 98, name: 'M6' },
      { id: 99, name: 'X3M' },
      { id: 100, name: 'X4M' },
      { id: 101, name: 'X5M' },
      { id: 102, name: 'X6M' },
      { id: 103, name: 'Autre modèle BMW' }
    ],

    'Buick': [
      { id: 110, name: 'Enclave' },
      { id: 111, name: 'Encore' },
      { id: 112, name: 'Envision' },
      { id: 113, name: 'LaCrosse' },
      { id: 114, name: 'Regal' },
      { id: 115, name: 'Verano' },
      { id: 116, name: 'Century' },
      { id: 117, name: 'LeSabre' },
      { id: 118, name: 'Park Avenue' },
      { id: 119, name: 'Autre modèle Buick' }
    ],
    'Cadillac': [
      { id: 120, name: 'ATS' },
      { id: 121, name: 'CTS' },
      { id: 122, name: 'XTS' },
      { id: 123, name: 'CT4' },
      { id: 124, name: 'CT5' },
      { id: 125, name: 'CT6' },
      { id: 126, name: 'XT4' },
      { id: 127, name: 'XT5' },
      { id: 128, name: 'XT6' },
      { id: 129, name: 'Escalade' },
      { id: 130, name: 'SRX' },
      { id: 131, name: 'CTS-V' },
      { id: 132, name: 'ATS-V' },
      { id: 133, name: 'Eldorado' },
      { id: 134, name: 'DeVille' },
      { id: 135, name: 'Autre modèle Cadillac' }
    ],
    'Chevrolet': [
      { id: 136, name: 'Spark' },
      { id: 137, name: 'Sonic' },
      { id: 138, name: 'Cruze' },
      { id: 139, name: 'Malibu' },
      { id: 140, name: 'Impala' },
      { id: 141, name: 'Camaro' },
      { id: 142, name: 'Corvette' },
      { id: 143, name: 'Trax' },
      { id: 144, name: 'Equinox' },
      { id: 145, name: 'Traverse' },
      { id: 146, name: 'Blazer' },
      { id: 147, name: 'Tahoe' },
      { id: 148, name: 'Suburban' },
      { id: 149, name: 'Colorado' },
      { id: 150, name: 'Silverado' },
      { id: 151, name: 'Volt' },
      { id: 152, name: 'Bolt' },
      { id: 153, name: 'Express' },
      { id: 154, name: 'Avalanche' },
      { id: 155, name: 'Monte Carlo' },
      { id: 156, name: 'Autre modèle Chevrolet' }
    ],
    'Chrysler': [
      { id: 157, name: '200' },
      { id: 158, name: '300' },
      { id: 159, name: 'Pacifica' },
      { id: 160, name: 'Voyager' },
      { id: 161, name: 'Town & Country' },
      { id: 162, name: 'Sebring' },
      { id: 163, name: 'Concorde' },
      { id: 164, name: 'Crossfire' },
      { id: 165, name: 'Autre modèle Chrysler' }
    ],

    'Dodge': [
      { id: 203, name: 'Caliber' },
      { id: 204, name: 'Avenger' },
      { id: 205, name: 'Charger' },
      { id: 206, name: 'Challenger' },
      { id: 207, name: 'Journey' },
      { id: 208, name: 'Durango' },
      { id: 209, name: 'Ram' },
      { id: 210, name: 'Caravan' },
      { id: 211, name: 'Grand Caravan' },
      { id: 212, name: 'Viper' },
      { id: 213, name: 'Dart' },
      { id: 214, name: 'Nitro' },
      { id: 215, name: 'Autre modèle Dodge' }
    ],

    'Fiat': [
      { id: 238, name: '500' },
      { id: 239, name: '500X' },
      { id: 240, name: '500L' },
      { id: 241, name: 'Panda' },
      { id: 242, name: 'Punto' },
      { id: 243, name: 'Tipo' },
      { id: 244, name: 'Bravo' },
      { id: 245, name: 'Linea' },
      { id: 246, name: 'Doblo' },
      { id: 247, name: 'Ducato' },
      { id: 248, name: 'Multipla' },
      { id: 249, name: 'Stilo' },
      { id: 250, name: 'Autre modèle Fiat' }
    ],
    'Ford': [
      { id: 251, name: 'Fiesta' },
      { id: 252, name: 'Focus' },
      { id: 253, name: 'Fusion' },
      { id: 254, name: 'Mondeo' },
      { id: 255, name: 'Taurus' },
      { id: 256, name: 'Mustang' },
      { id: 257, name: 'GT' },
      { id: 258, name: 'EcoSport' },
      { id: 259, name: 'Escape' },
      { id: 260, name: 'Edge' },
      { id: 261, name: 'Explorer' },
      { id: 262, name: 'Expedition' },
      { id: 263, name: 'Ranger' },
      { id: 264, name: 'F-150' },
      { id: 265, name: 'F-250' },
      { id: 266, name: 'F-350' },
      { id: 267, name: 'Transit' },
      { id: 268, name: 'Bronco' },
      { id: 269, name: 'Galaxy' },
      { id: 270, name: 'S-Max' },
      { id: 271, name: 'Kuga' },
      { id: 272, name: 'Puma' },
      { id: 273, name: 'Autre modèle Ford' }
    ],
    'Genesis': [
      { id: 274, name: 'G70' },
      { id: 275, name: 'G80' },
      { id: 276, name: 'G90' },
      { id: 277, name: 'GV60' },
      { id: 278, name: 'GV70' },
      { id: 279, name: 'GV80' },
      { id: 280, name: 'Coupe' },
      { id: 281, name: 'Autre modèle Genesis' }
    ],
    'GMC': [
      { id: 282, name: 'Canyon' },
      { id: 283, name: 'Sierra' },
      { id: 284, name: 'Terrain' },
      { id: 285, name: 'Acadia' },
      { id: 286, name: 'Yukon' },
      { id: 287, name: 'Denali' },
      { id: 288, name: 'Savana' },
      { id: 289, name: 'Envoy' },
      { id: 290, name: 'Jimmy' },
      { id: 291, name: 'Autre modèle GMC' }
    ],
    'Honda': [
      { id: 292, name: 'Fit' },
      { id: 293, name: 'Civic' },
      { id: 294, name: 'Accord' },
      { id: 295, name: 'Insight' },
      { id: 296, name: 'CR-V' },
      { id: 297, name: 'HR-V' },
      { id: 298, name: 'Pilot' },
      { id: 299, name: 'Passport' },
      { id: 300, name: 'Ridgeline' },
      { id: 301, name: 'Odyssey' },
      { id: 302, name: 'S2000' },
      { id: 303, name: 'NSX' },
      { id: 304, name: 'Element' },
      { id: 305, name: 'Jazz' },
      { id: 306, name: 'Prelude' },
      { id: 307, name: 'Autre modèle Honda' }
    ],
    'Hummer': [
      { id: 308, name: 'H1' },
      { id: 309, name: 'H2' },
      { id: 310, name: 'H3' },
      { id: 311, name: 'EV' },
      { id: 312, name: 'Autre modèle Hummer' }
    ],
    'Hyundai': [
      { id: 313, name: 'i10' },
      { id: 314, name: 'i20' },
      { id: 315, name: 'i30' },
      { id: 316, name: 'Accent' },
      { id: 317, name: 'Elantra' },
      { id: 318, name: 'Sonata' },
      { id: 319, name: 'Azera' },
      { id: 320, name: 'Genesis' },
      { id: 321, name: 'Kona' },
      { id: 322, name: 'Tucson' },
      { id: 323, name: 'Santa Fe' },
      { id: 324, name: 'Palisade' },
      { id: 325, name: 'Ioniq' },
      { id: 326, name: 'Veloster' },
      { id: 327, name: 'Matrix' },
      { id: 328, name: 'Tiburon' },
      { id: 329, name: 'Autre modèle Hyundai' }
    ],
    'Infiniti': [
      { id: 330, name: 'Q30' },
      { id: 331, name: 'Q40' },
      { id: 332, name: 'Q50' },
      { id: 333, name: 'Q60' },
      { id: 334, name: 'Q70' },
      { id: 335, name: 'QX30' },
      { id: 336, name: 'QX50' },
      { id: 337, name: 'QX60' },
      { id: 338, name: 'QX70' },
      { id: 339, name: 'QX80' },
      { id: 340, name: 'G35' },
      { id: 341, name: 'G37' },
      { id: 342, name: 'M35' },
      { id: 343, name: 'M37' },
      { id: 344, name: 'Autre modèle Infiniti' }
    ],
    'Isuzu': [
      { id: 345, name: 'D-Max' },
      { id: 346, name: 'MU-X' },
      { id: 347, name: 'Trooper' },
      { id: 348, name: 'Rodeo' },
      { id: 349, name: 'Ascender' },
      { id: 350, name: 'i-Series' },
      { id: 351, name: 'Autre modèle Isuzu' }
    ],

    'Jeep': [
      { id: 365, name: 'Wrangler' },
      { id: 366, name: 'Cherokee' },
      { id: 367, name: 'Grand Cherokee' },
      { id: 368, name: 'Compass' },
      { id: 369, name: 'Renegade' },
      { id: 370, name: 'Gladiator' },
      { id: 371, name: 'Liberty' },
      { id: 372, name: 'Patriot' },
      { id: 373, name: 'Commander' },
      { id: 374, name: 'Wagoneer' },
      { id: 375, name: 'Grand Wagoneer' },
      { id: 376, name: 'Autre modèle Jeep' }
    ],
    'Kia': [
      { id: 377, name: 'Picanto' },
      { id: 378, name: 'Rio' },
      { id: 379, name: 'Forte' },
      { id: 380, name: 'Optima' },
      { id: 381, name: 'Stinger' },
      { id: 382, name: 'K5' },
      { id: 383, name: 'Soul' },
      { id: 384, name: 'Seltos' },
      { id: 385, name: 'Sportage' },
      { id: 386, name: 'Sorento' },
      { id: 387, name: 'Telluride' },
      { id: 388, name: 'Carnival' },
      { id: 389, name: 'Sedona' },
      { id: 390, name: 'Niro' },
      { id: 391, name: 'EV6' },
      { id: 392, name: 'Spectra' },
      { id: 393, name: 'Magentis' },
      { id: 394, name: 'Autre modèle Kia' }
    ],
 

    'Land Rover': [
      { id: 423, name: 'Defender' },
      { id: 424, name: 'Discovery' },
      { id: 425, name: 'Discovery Sport' },
      { id: 426, name: 'Range Rover' },
      { id: 427, name: 'Range Rover Sport' },
      { id: 428, name: 'Range Rover Evoque' },
      { id: 429, name: 'Range Rover Velar' },
      { id: 430, name: 'Freelander' },
      { id: 431, name: 'LR2' },
      { id: 432, name: 'LR3' },
      { id: 433, name: 'LR4' },
      { id: 434, name: 'Autre modèle Land Rover' }
    ],
    'Lexus': [
      { id: 435, name: 'CT' },
      { id: 436, name: 'IS' },
      { id: 437, name: 'ES' },
      { id: 438, name: 'GS' },
      { id: 439, name: 'LS' },
      { id: 440, name: 'RC' },
      { id: 441, name: 'LC' },
      { id: 442, name: 'NX' },
      { id: 443, name: 'RX' },
      { id: 444, name: 'GX' },
      { id: 445, name: 'LX' },
      { id: 446, name: 'UX' },
      { id: 447, name: 'SC' },
      { id: 448, name: 'HS' },
      { id: 449, name: 'LFA' },
      { id: 450, name: 'Autre modèle Lexus' }
    ],
    'Lincoln': [
      { id: 451, name: 'MKZ' },
      { id: 452, name: 'Continental' },
      { id: 453, name: 'MKC' },
      { id: 454, name: 'Corsair' },
      { id: 455, name: 'MKX' },
      { id: 456, name: 'Nautilus' },
      { id: 457, name: 'MKT' },
      { id: 458, name: 'Aviator' },
      { id: 459, name: 'Navigator' },
      { id: 460, name: 'Town Car' },
      { id: 461, name: 'LS' },
      { id: 462, name: 'Zephyr' },
      { id: 463, name: 'Autre modèle Lincoln' }
    ],

    'Mazda': [
      { id: 487, name: 'Mazda2' },
      { id: 488, name: 'Mazda3' },
      { id: 489, name: 'Mazda6' },
      { id: 490, name: 'MX-5' },
      { id: 491, name: 'MX-30' },
      { id: 492, name: 'CX-3' },
      { id: 493, name: 'CX-5' },
      { id: 494, name: 'CX-7' },
      { id: 495, name: 'CX-9' },
      { id: 496, name: 'CX-30' },
      { id: 497, name: 'BT-50' },
      { id: 498, name: 'RX-7' },
      { id: 499, name: 'RX-8' },
      { id: 500, name: 'Tribute' },
      { id: 501, name: 'MPV' },
      { id: 502, name: 'Autre modèle Mazda' }
    ],

    'Mercedes-Benz': [
      { id: 515, name: 'Classe A' },
      { id: 516, name: 'Classe B' },
      { id: 517, name: 'Classe C' },
      { id: 518, name: 'Classe E' },
      { id: 519, name: 'Classe S' },
      { id: 520, name: 'CLA' },
      { id: 521, name: 'CLS' },
      { id: 522, name: 'SLK' },
      { id: 523, name: 'SLC' },
      { id: 524, name: 'SL' },
      { id: 525, name: 'AMG GT' },
      { id: 526, name: 'GLA' },
      { id: 527, name: 'GLB' },
      { id: 528, name: 'GLC' },
      { id: 529, name: 'GLE' },
      { id: 530, name: 'GLS' },
      { id: 531, name: 'Classe G' },
      { id: 532, name: 'EQC' },
      { id: 533, name: 'EQS' },
      { id: 534, name: 'EQA' },
      { id: 535, name: 'EQB' },
      { id: 536, name: 'Sprinter' },
      { id: 537, name: 'Vito' },
      { id: 538, name: 'Marco Polo' },
      { id: 539, name: 'Autre modèle Mercedes-Benz' }
    ],

    'Mini': [
      { id: 558, name: 'Cooper' },
      { id: 559, name: 'Cooper S' },
      { id: 560, name: 'Cooper SE' },
      { id: 561, name: 'Countryman' },
      { id: 562, name: 'Clubman' },
      { id: 563, name: 'Convertible' },
      { id: 564, name: 'Coupe' },
      { id: 565, name: 'Roadster' },
      { id: 566, name: 'Paceman' },
      { id: 567, name: 'John Cooper Works' },
      { id: 568, name: 'Autre modèle Mini' }
    ],
    'Mitsubishi': [
      { id: 569, name: 'Mirage' },
      { id: 570, name: 'Lancer' },
      { id: 571, name: 'Eclipse' },
      { id: 572, name: 'Galant' },
      { id: 573, name: 'ASX' },
      { id: 574, name: 'Eclipse Cross' },
      { id: 575, name: 'Outlander' },
      { id: 576, name: 'Pajero' },
      { id: 577, name: 'L200' },
      { id: 578, name: 'i-MiEV' },
      { id: 579, name: 'Endeavor' },
      { id: 580, name: 'Montero' },
      { id: 581, name: 'Autre modèle Mitsubishi' }
    ],
    'Nissan': [
      { id: 582, name: 'Versa' },
      { id: 583, name: 'Sentra' },
      { id: 584, name: 'Altima' },
      { id: 585, name: 'Maxima' },
      { id: 586, name: '370Z' },
      { id: 587, name: '350Z' },
      { id: 588, name: 'GT-R' },
      { id: 589, name: 'Juke' },
      { id: 590, name: 'Kicks' },
      { id: 591, name: 'Rogue' },
      { id: 592, name: 'Murano' },
      { id: 593, name: 'Pathfinder' },
      { id: 594, name: 'Armada' },
      { id: 595, name: 'Frontier' },
      { id: 596, name: 'Titan' },
      { id: 597, name: 'Leaf' },
      { id: 598, name: 'Ariya' },
      { id: 599, name: 'Micra' },
      { id: 600, name: 'Note' },
      { id: 601, name: 'Qashqai' },
      { id: 602, name: 'X-Trail' },
      { id: 603, name: 'Navara' },
      { id: 604, name: 'Autre modèle Nissan' }
    ],

    'Peugeot': [
      { id: 629, name: '108' },
      { id: 630, name: '208' },
      { id: 631, name: '2008' },
      { id: 632, name: '301' },
      { id: 633, name: '308' },
      { id: 634, name: '3008' },
      { id: 635, name: '508' },
      { id: 636, name: '5008' },
      { id: 637, name: 'Rifter' },
      { id: 638, name: 'Traveller' },
      { id: 639, name: 'Partner' },
      { id: 640, name: 'Expert' },
      { id: 641, name: 'Boxer' },
      { id: 642, name: 'e-208' },
      { id: 643, name: 'e-2008' },
      { id: 644, name: '206' },
      { id: 645, name: '207' },
      { id: 646, name: '307' },
      { id: 647, name: '407' },
      { id: 648, name: '607' },
      { id: 649, name: 'Autre modèle Peugeot' }
    ],

    'Pontiac': [
      { id: 657, name: 'G3' },
      { id: 658, name: 'G5' },
      { id: 659, name: 'G6' },
      { id: 660, name: 'G8' },
      { id: 661, name: 'Grand Prix' },
      { id: 662, name: 'Bonneville' },
      { id: 663, name: 'Grand Am' },
      { id: 664, name: 'Sunfire' },
      { id: 665, name: 'Vibe' },
      { id: 666, name: 'Torrent' },
      { id: 667, name: 'Montana' },
      { id: 668, name: 'Trans Am' },
      { id: 669, name: 'Firebird' },
      { id: 670, name: 'Solstice' },
      { id: 671, name: 'Autre modèle Pontiac' }
    ],
    'Porsche': [
      { id: 672, name: '911' },
      { id: 673, name: '718 Boxster' },
      { id: 674, name: '718 Cayman' },
      { id: 675, name: 'Panamera' },
      { id: 676, name: 'Macan' },
      { id: 677, name: 'Cayenne' },
      { id: 678, name: 'Taycan' },
      { id: 679, name: 'Boxster' },
      { id: 680, name: 'Cayman' },
      { id: 681, name: 'Carrera GT' },
      { id: 682, name: '918 Spyder' },
      { id: 683, name: '944' },
      { id: 684, name: '968' },
      { id: 685, name: 'Autre modèle Porsche' }
    ],
    'Ram': [
      { id: 686, name: '1500' },
      { id: 687, name: '2500' },
      { id: 688, name: '3500' },
      { id: 689, name: '4500' },
      { id: 690, name: '5500' },
      { id: 691, name: 'ProMaster' },
      { id: 692, name: 'ProMaster City' },
      { id: 693, name: 'Dakota' },
      { id: 694, name: 'Autre modèle Ram' }
    ],
    

    'Smart': [
      { id: 772, name: 'ForTwo' },
      { id: 773, name: 'ForFour' },
      { id: 774, name: 'Roadster' },
      { id: 775, name: 'CrossBlade' },
      { id: 776, name: 'EQForTwo' },
      { id: 777, name: 'EQForFour' },
      { id: 778, name: 'Autre ' }
    ],
    'Subaru': [
      { id: 779, name: 'Impreza' },
      { id: 780, name: 'Legacy' },
      { id: 781, name: 'Outback' },
      { id: 782, name: 'Forester' },
      { id: 783, name: 'Crosstrek' },
      { id: 784, name: 'Ascent' },
      { id: 785, name: 'WRX' },
      { id: 786, name: 'STI' },
      { id: 787, name: 'BRZ' },
      { id: 788, name: 'Baja' },
      { id: 789, name: 'Tribeca' },
      { id: 790, name: 'SVX' },
      { id: 791, name: 'Autre ' }
    ],
    'Suzuki': [
      { id: 792, name: 'Alto' },
      { id: 793, name: 'Celerio' },
      { id: 794, name: 'Swift' },
      { id: 795, name: 'Baleno' },
      { id: 796, name: 'Dzire' },
      { id: 797, name: 'Ciaz' },
      { id: 798, name: 'Ignis' },
      { id: 799, name: 'Vitara' },
      { id: 800, name: 'S-Cross' },
      { id: 801, name: 'Jimny' },
      { id: 802, name: 'Grand Vitara' },
      { id: 803, name: 'SX4' },
      { id: 804, name: 'Kizashi' },
      { id: 805, name: 'Autre' }
    ],
    'Tesla': [
      { id: 806, name: 'Model S' },
      { id: 807, name: 'Model 3' },
      { id: 808, name: 'Model X' },
      { id: 809, name: 'Model Y' },
      { id: 810, name: 'Cybertruck' },
      { id: 811, name: 'Roadster' },
      { id: 812, name: 'Semi' },
      { id: 813, name: 'Autre' }
    ],
    'Toyota': [
      { id: 814, name: 'Yaris' },
      { id: 815, name: 'Corolla' },
      { id: 816, name: 'Camry' },
      { id: 817, name: 'Avalon' },
      { id: 818, name: 'Prius' },
      { id: 819, name: 'C-HR' },
      { id: 820, name: 'RAV4' },
      { id: 821, name: 'Highlander' },
      { id: 822, name: '4Runner' },
      { id: 823, name: 'Sequoia' },
      { id: 813, name: 'Autre' }
    ],
    'Volkswagen': [
      { id: 178, name: 'Golf' },
      { id: 179, name: 'Passat' },
      { id: 180, name: 'Tiguan' },
      { id: 181, name: 'Jetta' },
      { id: 182, name: 'Polo' },
      { id: 183, name: 'Autre modèle Volkswagen' }
    ],
    'Volvo': [
      { id: 184, name: 'XC40' },
      { id: 185, name: 'XC60' },
      { id: 186, name: 'XC90' },
      { id: 187, name: 'S60' },
      { id: 188, name: 'V60' },
      { id: 189, name: 'Autre modèle Volvo' }
    ],
    'Autre marque': [
      { id: 190, name: 'Autre modèle' }
    ],
  
  


},  getBrands() {
    return this.brands;
  },
  vehicleColors: [
    { id: 1, name: 'Blanc' },
    { id: 2, name: 'Noir' },
    { id: 3, name: 'Gris' },
    { id: 4, name: 'Argent' },
    { id: 5, name: 'Bleu' },
    { id: 6, name: 'Rouge' },
    { id: 7, name: 'Vert' },
    { id: 8, name: 'Jaune' },
    { id: 9, name: 'Orange' },
    { id: 10, name: 'Marron' },
    { id: 11, name: 'Beige' },
    { id: 12, name: 'Rose' },
    { id: 13, name: 'Violet' },
    { id: 14, name: 'Or' },
    { id: 15, name: 'Autre couleur' }
  ],
  vehicleTypes: [
    { id: 1, name: 'Berline' },
    { id: 2, name: 'SUV' },
    { id: 3, name: 'Break' },
    { id: 4, name: 'Crossover' },
    { id: 5, name: 'Monospace' },
    { id: 6, name: 'Cabriolet' },
    { id: 7, name: 'Coupé' },
    { id: 8, name: 'Utilitaire' },
    { id: 9, name: '4x4' },
    { id: 10, name: 'Autre type' }],

  

  getModelsByBrand(brandName) {
    return this.modelsByBrand[brandName] || [{ id: 999, name: 'Autre modèle' }];
  },
   getVehicleTypes() {
    return this.vehicleTypes;
  },

  getVehicleColors() {
    return this.vehicleColors;
  },

  getSeatingCapacities() {
    return [
      { id: 1, name: '1 places' },
      { id: 2, name: '2 places' },
      { id: 3, name: '3 places' },
      { id: 4, name: '4 places' },
      { id: 5, name: '5 places' },
      { id: 6, name: '6 places' },
      { id: 7, name: '7 places' },
      { id: 8, name: '8 places' },
      { id: 9, name: '8 places' },
      { id: 10, name: '10 places' },
      { id: 11, name: '11 places' },
      { id: 12, name: '12 places' },
    ];
}}
