"""ajout colonne user_id dans Trip

Revision ID: 324a6157b222
Revises: 23dba2085af8
Create Date: 2025-07-09 02:45:05.268145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324a6157b222'
down_revision: Union[str, None] = '23dba2085af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('car_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_trips_car_id'), 'trips', ['car_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_car_id'), table_name='trips')
    op.drop_column('trips', 'car_id')
    # ### end Alembic commands ###
