"""ajout table User

Revision ID: a3fb71b51899
Revises: a1403af9c209
Create Date: 2025-07-11 01:29:06.144212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fb71b51899'
down_revision: Union[str, None] = 'a1403af9c209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('type_of_car', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'type_of_car')
    # ### end Alembic commands ###
