"""add_denormalized_fields_to_payments KJ

Revision ID: b4a4cbed9005
Revises: 83c64f7bf9e7
Create Date: 2025-11-11 17:29:26.731261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a4cbed9005'
down_revision: Union[str, None] = '83c64f7bf9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_earnings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.Enum('PENDING_TRIP', 'PAYABLE', 'REQUESTED', 'PROCESSING', 'PAID', 'FAILED', name='earningstatus'), nullable=False),
    sa.Column('trip_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('payable_at', sa.DateTime(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payout_request_id', sa.UUID(), nullable=True),
    sa.Column('passenger_name', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['payout_request_id'], ['payout_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_earnings_driver_id'), 'driver_earnings', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_earnings_status'), 'driver_earnings', ['status'], unique=False)
    op.create_index(op.f('ix_driver_earnings_trip_id'), 'driver_earnings', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_earnings_trip_id'), table_name='driver_earnings')
    op.drop_index(op.f('ix_driver_earnings_status'), table_name='driver_earnings')
    op.drop_index(op.f('ix_driver_earnings_driver_id'), table_name='driver_earnings')
    op.drop_table('driver_earnings')
    # ### end Alembic commands ###
