"""Ajout de updated_at à bookings

Revision ID: e6ded93b4b95
Revises: 9caa0065e82f
Create Date: 2025-10-09 07:57:52.836204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ded93b4b95'
down_revision: Union[str, None] = '9caa0065e82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('id_trip', sa.UUID(), nullable=False),
    sa.Column('id_stop', sa.UUID(), nullable=True),
    sa.Column('id_driver', sa.UUID(), nullable=False),
    sa.Column('number_of_seats', sa.Integer(), nullable=False),
    sa.Column('price_per_seat', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('reservation_fee_per_seat', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=4), nullable=False),
    sa.Column('tax_region', sa.String(length=16), nullable=False),
    sa.Column('base_total', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('fee_total', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('charged_now_total', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('driver_payable', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('driver_collected_cash', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('free_cancellation_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chauffeur_payment_method', sa.Enum('cash', 'virement', name='modeofpayment'), nullable=False),
    sa.Column('payment_method_used', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', 'completed', 'failed', name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('idx_bookings_trip', 'bookings', ['id_trip'], unique=False)
    op.create_index('idx_bookings_user', 'bookings', ['id_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bookings_user', table_name='bookings')
    op.drop_index('idx_bookings_trip', table_name='bookings')
    op.drop_index('idx_bookings_status', table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
