"""add_denormalized_fields_to_payments

Revision ID: 83c64f7bf9e7
Revises: c57a036f7999
Create Date: 2025-11-11 17:25:02.394631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83c64f7bf9e7'
down_revision: Union[str, None] = 'c57a036f7999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'PROCESSING', 'PAID', 'FAILED', 'CANCELLED', name='payoutstatus'), nullable=False),
    sa.Column('bank_account_last4', sa.String(length=4), nullable=True),
    sa.Column('transfer_reference', sa.String(length=50), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('eta_date', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_requests_driver_id'), 'payout_requests', ['driver_id'], unique=False)
    op.create_index(op.f('ix_payout_requests_status'), 'payout_requests', ['status'], unique=False)
    op.add_column('payments', sa.Column('chauffeur_payment_method', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('driver_payable', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payments', sa.Column('trip_departure_city', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('trip_destination_city', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('trip_departure_date', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('passenger_name', sa.String(length=100), nullable=True))
    op.alter_column('payments', 'driver_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=3),
               existing_nullable=True)
    op.alter_column('payments', 'fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('payments', 'tax_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('payments', 'tax_region',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('payments', 'stripe_receipt_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='paymentstatus'),
               nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_driver_id'), 'payments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_trip_id'), 'payments', ['trip_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'payments', ['stripe_payment_intent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_trip_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_driver_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.alter_column('payments', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'payment_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='paymentstatus'),
               nullable=True)
    op.alter_column('payments', 'stripe_receipt_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('payments', 'tax_region',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('payments', 'tax_rate',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('payments', 'fee',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('payments', 'driver_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('payments', 'passenger_name')
    op.drop_column('payments', 'trip_departure_date')
    op.drop_column('payments', 'trip_destination_city')
    op.drop_column('payments', 'trip_departure_city')
    op.drop_column('payments', 'driver_payable')
    op.drop_column('payments', 'chauffeur_payment_method')
    op.drop_index(op.f('ix_payout_requests_status'), table_name='payout_requests')
    op.drop_index(op.f('ix_payout_requests_driver_id'), table_name='payout_requests')
    op.drop_table('payout_requests')
    # ### end Alembic commands ###
