"""ajout table users

Revision ID: ee6f7bf5f5a8
Revises: e6ded93b4b95
Create Date: 2025-10-23 21:17:09.883633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6f7bf5f5a8'
down_revision: Union[str, None] = 'e6ded93b4b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_bookings_driver', 'bookings', ['id_driver'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bookings_driver', table_name='bookings')
    # ### end Alembic commands ###
