"""create tables trip, stop, preference

Revision ID: aa34a69e23ab
Revises: dce3f9ea9de1
Create Date: 2025-06-25 22:27:14.036897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa34a69e23ab'
down_revision: Union[str, None] = 'dce3f9ea9de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('departure_city', sa.String(), nullable=False),
    sa.Column('destination_city', sa.String(), nullable=False),
    sa.Column('departure_place', sa.String(), nullable=False),
    sa.Column('destination_place', sa.String(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_departure_city'), 'trips', ['departure_city'], unique=False)
    op.create_index(op.f('ix_trips_departure_date'), 'trips', ['departure_date'], unique=False)
    op.create_index(op.f('ix_trips_destination_city'), 'trips', ['destination_city'], unique=False)
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_destination_city'), table_name='trips')
    op.drop_index(op.f('ix_trips_departure_date'), table_name='trips')
    op.drop_index(op.f('ix_trips_departure_city'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
