"""create tables trip, stop, preference

Revision ID: dce3f9ea9de1
Revises: 32aa4258b0a1
Create Date: 2025-06-25 22:23:51.269411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce3f9ea9de1'
down_revision: Union[str, None] = '32aa4258b0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
